### ISSUE TITLE
No append on ImageProcessing::Vips

### ISSUE THREAD

**Issue by doutatsu** [janko/image_processing#122]
Documentation has a link to `append`, but it leads nowhere and when trying to call it, the result is as follows:
<img width="421" alt="image" src="https://github.com/janko/image_processing/assets/4270980/40ea520e-98c7-4090-8673-527f9ea60833">

**Comment by janko** [comment]
Thanks, that was left over from copy-pasting MiniMagick documentation, I'll remove that link.

**Comment by doutatsu** [comment]
@janko Is it not possible to append then in Vips?

**Comment by janko** [comment]
@doutatsu The MiniMagick's `#append` API is for adding raw CLI arguments to the command, vips backend doesn't have an equivalent, because it doesn't execute a shell command.

I think vips equivalent of ImageMagick's `-append` is [`#join`](https://www.rubydoc.info/gems/ruby-vips/Vips/Image#join-instance_method). Something like this should work:

```rb
ImageProcessing::Vips
  .source("...")
  .join(Vips::Image.new_from_file("..."), direction :horizontal)
```

**Comment by doutatsu** [comment]
@janko I guess I should dive into Vips documentation first, as I need things like `-coalesce` or `-layers`, which I use append for currently with magick. Thanks for the headsup
