### ISSUE TITLE
Utilize libvips' shrink-on-load when resizing

### ISSUE THREAD

**Issue by janko** [janko/image_processing#48]
The `thumbnail_image()` function (or `Vips::Image#thumbnail_image` in ruby-vips) introduced in libvips 8.6 allows resizing an already loaded image, which initially fitted nicely into the ImageProcessing gem, because now resizing is just another processing step that can be added anywhere in the pipeline.

```rb
image = Vips::Image.new_from_file("/path/to/image")
# ...
image.thumbnail_image(width, height: height)
# ...
image.write_to_file("...")
```

However, after a discussion with the libvips author (https://github.com/libvips/libvips/issues/1227#issuecomment-462267695), I found out that `thumbnail_image()` is generally much **slower** (and in certain cases less correct) than using `thumbnail()` (or `Vips::Image.thumbnail` in ruby-vips) which resizes the image at load time.

```rb
image = Vips::Image.thumbnail("/path/to/image", width, height: height) # this is much faster
# ...
image.write_to_file("...")
```

I would like to find a way to support resizing on load with `Vips::Image.thumbnail` in ImageProcessing. My idea was that the existing `#resize_*` macros would work in that mode as well. I don't know what would be the best way to support this.

cc @mokolabs @hmistry @jrochkind

**Comment by janko** [comment]
I was first thinking of adding a dedicated API for "resize on load", and encourage people to use that. But now I'm thinking just to apply this as an optimization when

* `#resize_*` is the first operation
* `#loader` options are empty (since `Vips::Image.thumbnail` doesn't accept loader options)

So,

```rb
ImageProcessing::Vips
  .source(image)
  .resize_to_fit(400, 400) # it's the first operation
  .flip(:vertical)
  .call
```

would apply the optimization (using `Vips::Image.thumbnail` to load the image), while

```rb
ImageProcessing::Vips
  .source(image)
  .crop(800, 900)
  .resize_to_fit(400, 400) # it's the second operation
  .call
```

or 

```rb
ImageProcessing::Vips
  .source(image)
  .resize_to_fit(400, 400) # it's the first operation, but there are loader options
  .loader(fail: true)
  .call
```

would not apply the optimization.

What I like about this solution is that users would just keep using the same API, we wouldn't need to introduce anything new. The downside is that users would have suboptimal performance if they performed any operations before resizing which could just as well be performed after (e.g. grayscaling). However, the documentation would say that having `#resize_*` as the first operation is faster, so hopefully that's not so bad. In any case, it's an improvement over status quo, so users would have same or better performance.

**Comment by hmistry** [comment]
There are 2 approaches I can think of:
1. change under-the-hood for `resize_*` to use `Vips::Image.thumbnail` so existing users can get the benefit at the risk of breaking some cases like where `loader` options doesn't work
2. have a dedicated API by adding a method like `#resize_on_load` or a param option to switch to `Vips::Image.thumbnail` e.g.

```
ImageProcessing::Vips
  .source(image)
  .resize_on_load # if present, uses thumbnail() otherwise uses thumbnail_image()
  .resize_to_fit(400, 400)
  .flip(:vertical)
  .call
```

I'd prefer the second one because it's explicit. I understand existing users have to change over to get the benefit but we're not breaking their existing apps and if they need more performance, they are explicitly making the change, testing, and are aware some options don't work. The first option is great when it's fully compatible drop-in -  in which case you wouldn't even ask.

While your idea above is clever, I'm not a fan of it because that will cause maintenance issues. Some one will implement it correctly the first time and in future others may change the order or something and now we unintentionally switched from `thumbnail()` to `thumbnail_image()`. This makes the API unpredictable when using it without diligently checking the documentation. I faced a similar issue with an Active Record query and it was a pain to get right because order mattered and to make sure anyone who touched it did not change its outcome.

**Comment by janko** [comment]
@hmistry Thanks for chiming in.

> 1\. change under-the-hood for `resize_*` to use `Vips::Image.thumbnail` so existing users can get the benefit at the risk of breaking some cases like where `loader` options doesn't work

It's not only with `loaders`, it's backwards incompatible change because processing steps aren't generally commutative (imagine cropping then resizing). So I don't think it's feasible. Also, I think it could be unexpected behaviour if `#resize_*` is always applied first, no matter where it's positioned. But I see your reasoning, in many cases it probably wouldn't cause any problems.

> 2\. have a dedicated API by adding a method like `#resize_on_load` or a param option to switch to `Vips::Image.thumbnail` e.g.

So, the `#resize_on_load` switch would affect a `#resize_*` operation in that chain? I'm not sure I like that users have to opt-in to get fast behaviour. I would rather if we can find a way where they can opt-out to get slow behaviour.

I hear your concerns about users being able to accidentally slow down their performance. I can totally see this happening, and I wouldn't want them to have to carefully read the documentation to find that out.

What do you think about a modification to my approach, with the following change: if `#resize_*` is *not* the first operation, we print out a warning? The users can get rid of the warning in two or even three ways:

1. move the `#resize_*` operation as the first step
2. add `loader(resize: false)` into the chain, making it intentional that we don't want resize on load
3. add `loader(resize: true)` into the chain, making the `#resize_*` operation applied on load (this is like your `#resize_on_load` switch)

**Comment by hmistry** [comment]
> the `#resize_on_load` switch would affect a `#resize_*` operation in that chain?

Yes - it's one idea.

> I'm not sure I like that users have to opt-in to get fast behaviour. I would rather if we can find a way where they can opt-out to get slow behaviour.

Ok that's your goal. How to make this work... I can't think of other options than your proposed ones, so we can...
1. Highlight the potential breaking change in CHANGELOG
2. Add a post install message when this gem is installed
3. A warning is an option but it can be hit or miss. Some dev's don't read it and others may not like warnings polluting their production logs especially. Will this warning always stay in future release versions or will be phased out at some point?
4. `loader(resize: true/false)` is acceptable but the naming of `resize` is not indicative of on-load so I'd rather it be named `on_load` or `resize_on_load`
5. To minimize bad edge cases with this change we can have additional checks like if `resize(400x400) is used together with `crop(800x900)` (we know crop size will typically be bigger than resize), then fallback to no-load option regardless if resize is first step. It's going to create a complex ruleset.

I have 2 reasons that make me feel a little uncomfortable with this change:
1. the potential disruption to devs in production on gem update if they don't check warnings/modify their code on gem update
2. there's a small shift in the chainable API from being commutative to not for resize. While this is not so bad, one can no longer simply assume the API design is commutative or not commutative because it will now be commutative except for this one case. I'd hate to see these exceptions go from one case (tolerable) to several cases (confusing) because then the API lacks consistency and now dev's have to keep track of when it's commutative or not.

We can go ahead and try it... maybe introduce a beta version and ping some people to try it. Either way we'll learn from the experience. 😃

**Comment by hmistry** [comment]
I just thought of another option... actually what if we simply looked at all the options in the pipeline and then determine whether to use on-load or not optimization? If we see any incompatible options like `crop`, `loader` options, `loader(resize_on_load: false)`, we use the current method and if not, we use the optimized version. This might be simpler in many ways and only triggers my first concern, not the second.

**Comment by janko** [comment]
> Highlight the potential breaking change in CHANGELOG

I think we might have misunderstood each other. My original proposal wouldn't have any backwards incompatible changes. What I meant with "opt-out to get slow behaviour" was that the optimization is applied automatically when `#resize_*` is the first operation (which should maintain the same behaviour, it would only be faster), but if it's not, a warning would be printed telling the user that it's not optimal because we cannot use shrink-on-load, but `thumbnail_image()` would still be used normally.

> 1\. the potential disruption to devs in production on gem update if they don't check warnings/modify their code on gem update

So, just to clarify, there should be no disruption, ImageProcessing gem would work correctly regardless of where `#resize_*` is specified. You'd only get a warning telling you to try to make it `#resize_` the first operation (or add `loader(resize: false)` to say that it's intentionally not the first one).

> 2\. there's a small shift in the chainable API from being commutative to not for resize.

I'm not sure I understood this concern. Processing operations have never been commutative; the order in which you specify operations is the order in which they will get executed. But processing operations as a whole are commutative with `loader`, `saver`, `convert`, and `source`.

> what if we simply looked at all the options in the pipeline and then determine whether to use on-load or not optimization? If we see any incompatible options like `crop`, `loader` options, `loader(resize_on_load: false)`, we use the current method and if not, we use the optimized version.

Let me check if I'm understanding you correctly. If there are operations A - B - C, and C was a `#resize_*` operation, you want ImageProcessing to somehow determine whether it's "safe" to move C to the beginning and that C - A - B would still produce the correct result? I think that wouldn't be feasible, libvips has tons of operations, ImageProcessing cannot know when it's safe to change the order.

What I proposed was that if there are *any* prior processing operations, or *any* `loader` options, we don't apply the optimization, because we cannot know whether we can safely change the order.

**Comment by hmistry** [comment]
@janko Yeah I got a little confused thinking of the various edge cases and I misunderstood this part when I quickly looked at the code:

> Processing operations have never been commutative; the order in which you specify operations is the order in which they will get executed. But processing operations as a whole are commutative with `loader`, `saver`, `convert`, and `source`.

In reviewing the code, I deduced it was only commutative because it seemed the options where combined in the builder and then `call` executes it. But I see how that will be a problem and you need to maintain the sequence of operations.

Ok so what you are proposing is perfectly fine then and will work. The only "issue" will be the difference in quality if any and in a good way I imagine. Sorry for any confusion caused. 

I wouldn't put the informative warning to use faster option unless you want to experiment with that UX paradigm. There is an appeal factor to it - here's a library that tells you how to improve your code! In Bundler, we got complaints for informative warnings of new updates (slightly different use case). I think a post gem install message might be a better place - it won't be as prominent as your version but it also won't be annoying to constantly get the warnings and make changes to stop it (depends on the mood).

**Comment by jrochkind** [comment]
i wouldn't bother with a gem post-install message. I think few see it, and those who do find it annoying, actually precisely becuase of how bundler changes workflow. Just release notes is as likely to be seen as anywhere probably.

**Comment by janko** [comment]
Yeah, I also don't think it's an important enough change to warrant a post-install message, I would typically use it if there is a big breaking change (and this wouldn't be a breaking change at all).

I still think a warning message might be nice, because it really can make a significant performance difference when resizing larger images:

```rb
require "vips"
require "down"
require "benchmark"

# disable cache
Vips.vips_cache_set_max 0

1000.step(by: 500, to: 3000) do |source_width|
  source = Down.download("https://images.unsplash.com/photo-1549221838-126dc3ebf29f?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=#{source_width}")

  [300, 500, 800].each do |target_width|
    thumbnail_image_duration = Benchmark.realtime do
      image = Vips::Image.new_from_file(source.path)
      image.thumbnail_image(target_width, height: Vips::MAX_COORD)
      image.write_to_buffer(".jpg")
    end

    thumbnail_duration = Benchmark.realtime do
      image = Vips::Image.thumbnail(source.path, target_width, height: Vips::MAX_COORD)
      image.write_to_buffer(".jpg")
    end

    puts "thumbnail_image() (#{source_width}px => #{target_width}px) – #{"%.3f" % thumbnail_image_duration}s"
    puts "thumbnail()       (#{source_width}px => #{target_width}px) – #{"%.3f" % thumbnail_duration}s"
    puts
  end
end
```
```
thumbnail_image() (1000px => 300px) – 0.062s
thumbnail()       (1000px => 300px) – 0.031s

thumbnail_image() (1000px => 500px) – 0.045s
thumbnail()       (1000px => 500px) – 0.043s

thumbnail_image() (1000px => 800px) – 0.046s
thumbnail()       (1000px => 800px) – 0.043s

thumbnail_image() (1500px => 300px) – 0.104s
thumbnail()       (1500px => 300px) – 0.037s

thumbnail_image() (1500px => 500px) – 0.096s
thumbnail()       (1500px => 500px) – 0.068s

thumbnail_image() (1500px => 800px) – 0.090s
thumbnail()       (1500px => 800px) – 0.066s

thumbnail_image() (2000px => 300px) – 0.154s
thumbnail()       (2000px => 300px) – 0.041s

thumbnail_image() (2000px => 500px) – 0.170s
thumbnail()       (2000px => 500px) – 0.051s

thumbnail_image() (2000px => 800px) – 0.147s
thumbnail()       (2000px => 800px) – 0.093s

thumbnail_image() (2500px => 300px) – 0.219s
thumbnail()       (2500px => 300px) – 0.046s

thumbnail_image() (2500px => 500px) – 0.218s
thumbnail()       (2500px => 500px) – 0.053s

thumbnail_image() (2500px => 800px) – 0.215s
thumbnail()       (2500px => 800px) – 0.123s

thumbnail_image() (3000px => 300px) – 0.300s
thumbnail()       (3000px => 300px) – 0.046s

thumbnail_image() (3000px => 500px) – 0.310s
thumbnail()       (3000px => 500px) – 0.076s

thumbnail_image() (3000px => 800px) – 0.302s
thumbnail()       (3000px => 800px) – 0.146s
```

**Comment by hmistry** [comment]
Wow... pretty big difference!

**Comment by janko** [comment]
For now I decided not to print any warning message, but just to recommend it in the README. We can iterate on that afterwards if we want.

**Comment by renchap** [comment]
What about methods like `.saver` which, if I understand correctly, are not a proper operation?

**Comment by hmistry** [comment]
@renchap I'm not familiar with `.saver` but I believe if it's present in `options`, then the code will default to using `thumbnail_image`. It would make sense to ignore it if it's not a proper operation.

We chose to keep the logic for choosing `thumbnail` simple for now i.e. `resize_*` must be first and there are no options. Maybe in future we can incorporate more cases depending on how this goes. (See the [logic](https://github.com/janko/image_processing/blob/master/lib/image_processing/vips.rb#L37-L39) in code.)

**Comment by renchap** [comment]
Thanks! I will change my code then :)

My usecase: I have different saving options depending on the type of image (as you cant set JPEG-specific options for a PNG), and it allowed me to do something like:
```ruby
    pipeline = if metadata["mime_type"] == "image/jpeg"
                 ImageProcessing::Vips.source(file)
                                      .saver(quality: 90, interlace: true, strip: true)
               else
                 ImageProcessing::Vips.source(file)
               end

    versions = {}

    versions[:s1800] = pipeline.resize_to_limit!(1800, 1800) if metadata["width"] > 1800 || metadata["height"] > 1800
    versions[:s1200] = pipeline.resize_to_limit!(1200, 1200)
```

**Comment by hmistry** [comment]
Thanks for sharing your use case. It helps us build our edge case matrix. 

I don't see a need to change your code unless you want to eliminate the `.saver` options. `thumbnail` in Vips is more restricted in options than `thumbnail_image` hence our decision.

Your `versions[:s1800]` will use `thumbnail_image` and you probably want to keep the options especially interlace. The `versions[:s1200]` will use the faster `thumbnail`.

**Comment by janko** [comment]
This discussion made me realize that it's not so obvious what is an operation and what isn't.

* `resize_*`, other macros, and libvips functions are operations
* `source`, `saver`, `loader`, and `convert` are not operations

As I said I said in the beginning of the PR and in the docs, resize-on-load will be applied if `#resize_*` is the first operation and there aren't any `loader` options. The reason for this is because instead of `Vips::Image.new_from_file`, which accepts load options, we would be using `Vips::Image.thumbnail`, which doesn't accept load options. If the user specified `loader` options, we must use `Vips::Image.new_from_file` to load the image, otherwise we cannot apply them.

Any other options such as `saver` and `convert` are applicable regardless of how we load the image, so they're not reason to skip resize-on-load. @renchap your example will use resize-on-load, no changes are needed.

**Comment by hmistry** [comment]
> This discussion made me realize that it's not so obvious what is an operation and what isn't.

True. Also operations and options both start with "op" so when reading your brain might auto-predict/auto-correct the wrong one and cause more confusion. Haha. 😛

**Comment by renchap** [comment]
Thanks for clarifying what are operations!
