### ISSUE TITLE
SVG support without extension

### ISSUE THREAD

**Issue by gencer** [janko/image_processing#49]
I have JPG, PNG, PDF and SVG files resides in `uploads/` dir and I load JPG and PNG like this:

```ruby
  file_path = 'uploads/jpg_file_without_extension'
  ImageProcessing::Vips
          .source(file_path)
          .resize_to_fit(size, size, crop: 'centre')
          .convert("jpg")
          .call(destination: "#{output}/#{size}.jpg")
```

and it works with JPG and PNG files.

However, When there is a SVG file resides in dir, I get this error:

`Vips::Error: VipsForeignLoad: "uploads/f131ddc1f188" is not a known file format`

When I append .svg at the end it works.

So my question is, How can I tell the gem that file is SVG? Any additional parameter exists for such scenario? (I already know which file is it in db)

Ah and one more thing, When Creating JPG from SVG, is it possible to specify background as white instead of black? I've done these in go app using vips bu can't figure it out with this gem.

**Comment by janko** [comment]
ImageProcessing gem internally calls

```rb
Vips::Image.new_from_file(file_path)
```

to load the image, requiring libvips to determine the filetype in order to use the appropriate loader. 

With your SVG image without a file extension, does specifying a loader explicitly work:

```rb
Vips::Image.svgload(file_path)
```

If so, we could add an option to ImageProcessing gem for specifying the loader, e.g:

```rb
ImageProcessing
  .source(file_path)
  .loader(loader: :svg)
  # ..
```

**Comment by gencer** [comment]
Yes, svgload loads the file without extension. This is how I currently using it.

This will be awesome if you can add this option. But not just limited to svg but also for pdf, jpg, png. Basically loader must accept all available loaders..

**Comment by janko** [comment]
@gencer I pushed a commit that adds `:loader` (and `:saver`) option as describe. Could you test whether it works? Afterwards I can push a new gem version.

Btw, I'd suggest also reporting on https://github.com/libvips/libvips that you have a SVG which libvips wasn't able to correctly identify. Perhaps that's something that can be fixed in libvips.

**Comment by gencer** [comment]
Awesome!

Tested with `svg`, `jpg` and `png`. It works!

**Comment by janko** [comment]
Version 1.9.0 released which includes this addition.
