### ISSUE TITLE
`auto_rotate` doesn't work as expected but it works on another language with same `libvips`.

### ISSUE THREAD

**Issue by gencer** [janko/image_processing#52]
I'm uploading an image and process it in Go app. This go app also using `libvips`. It auto rotates based on `exif` status.

However, When I switch to Ruby, autorotate stop working. My image is 90-degree rotated while in windows, i can see correctly. Also on Go-side everything is as expected.

What Am I missing here?

This is the last piece of code I tried.

Used libvips `8.8.0-rc3`
```
      pipeline = ImageProcessing::Vips.source(file_path)
      loader = :jpg # or empty if no loader specified
      pipeline.loader(autorotate: true, autorot: false, loader: loader) unless loader.nil?
      pipeline.resize_to_fit(size, size, crop: 'centre')
              .convert('png')
              .call(destination: "img.png")
```

**Comment by janko** [comment]
@gencer The `ImageProcessing::Builder` object that you chain the methods doesn't mutate when you call `#loader` or other methods on it. So you always need to save the result back:

```rb
pipeline = ImageProcessing::Vips.source(file_path)
# ...
pipeline = pipeline.loader(...) if loader.nil?
pipeline...
```

**Comment by gencer** [comment]
hey @janko. Oh, I was thought it was mutating. Gotcha. However, my image is still not properly rotated.

Here:
```

        pipeline = ImageProcessing::Vips.source(file_path)
        pipeline = pipeline.loader(autorotate: true, autorot: false, loader: :jpeg)
        pipeline.resize_to_fit(size, size, crop: 'centre')
                .convert('png')
                .call(destination: "#{output}/#{size}.png")
```

BTW, without `loader` (in case loader in `nil`)  how can I auto-rotate image? Is there an another method to call for this?

**Comment by janko** [comment]
Oh, I got it. When `ImageProcessing::Vips` uses resize-on-load (which is your case), `Processor.load_image` will be skipped and instead `Processor#resize_to_fit` will be called directly. Autorotating should normally be turned by default, but it wasn't in this case because I forgot to pass the autorotate option to `Vips::Image.thumbnail`. I'll push a fix shortly and release a new version.

**Comment by janko** [comment]
Hmm, I couldn't get a failing test. And now I see in the [`vips_thumbnail()`](https://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail) documentation that `auto_rotate` is actually turned on by default, so it should already be working fine.

There is a possibility that libvips doesn't know how to autorotate your particular image (or the necessary metadata is missing). Just to verify this, when you run the following script with your image path, are any of the image outputs autorotated?

```rb
require "vips"

file_path = "/path/to/your/image"

Vips::Image
  .new_from_file(file_path, autorotate: true)
  .write_to_file("autorotated_1.png")

Vips::Image.new_from_file(file_path)
  .autorot
  .write_to_file("autorotated_2.png")

Vips::Image
  .jpegload(file_path, autorotate: true)
  .write_to_file("autorotated_3.png")

Vips::Image
  .thumbnail(file_path, size, height: size)
  .write_to_file("autorotated_4.png")

Vips::Image
  .thumbnail(file_path, size, height: size, auto_rotate: true)
  .write_to_file("autorotated_5.png")
```

**Comment by gencer** [comment]
Interesting. In windows, output is autorotated.
On Linux, it is wrongly rotated...

But, if windows shows me properly, it means there is a metadata info in it. So there must be something in vips to turn on or off.

**Comment by gencer** [comment]
Btw, fourth and fifth samples are missing. Fourth has the same output when I gave a `size`.

Fifth example fails due to:

```
unable to call thumbnail: unknown option auto_rotate (Vips::Error)
```

**Comment by janko** [comment]
Wow, that's really strange behaviour. I cannot fully replicate your conditions, because I'm on a Mac and have libvips 8.7.4 installed. But when I run the script with your image, I get the correctly rotated image. 

And for me the fifth example doesn't fail. Maybe libvips 8.8 introduced a bug that should be reported. There were some changes around `:auto_rotate`, in [What's new in 8.8](http://libvips.github.io/libvips/2019/04/22/What's-new-in-8.8.html) it says:

> The auto_rotate flag to `thumbnail` is now always on and does nothing if you try to set it.

I'd definitely recommend reporting it to the `libvips` repo, the lead maintainer is very responsive and helpful. He also maintains `ruby-vips`, so there won't be any troubles with Ruby examples 😉

Since this doesn't appear to be a problem in ImageProcessing gem, I'll close this issue for now.

**Comment by janko** [comment]
Actually, we can keep it open until the `libvips` maintainer confirms.

**Comment by janko** [comment]
Ok, the libvips issue has been resolved, closing.
