### ISSUE TITLE
Using a Tempfile source raises ImageProcessing::Error

### ISSUE THREAD

**Issue by timcraft** [janko/image_processing#53]
Using a Tempfile source raises the "Source format is multi-layer, but destination format is single-layer..." exception from the #disallow_split_layers! method. Script to reproduce:

```ruby
require 'image_processing/mini_magick'
require 'tempfile'

path = ARGV.first

pipeline = ImageProcessing::MiniMagick.thumbnail('200x')

tempfile = Tempfile.new(File.basename(path))

# Simulate downloading an image to a tempfile
FileUtils.cp(path, tempfile.path)

# Using the tempfile raises ImageProcessing::Error
p pipeline.call(tempfile)

# Using the tempfile path raises ImageProcessing::Error
# p pipeline.call(tempfile.path)

# Using the original path works
# p pipeline.call(path)
```

(Run with a path to a .jpg or .png file argument.)

The README specifies `The source object needs to responds to #path` so I would expect it to be usable with a tempfile source? Looking at the code I'm guessing the #disallow_split_layers! method is making an assumption about paths which breaks with the tempfile input?

**Comment by janko** [comment]
The problem is not the Tempfile argument, but that the Tempfile you're created doesn't have an extension, and it's used as the destination path. I think that confused ImageMagick, maybe it doesn't know to which format you want to convert. I'm not able to reproduce that, however, for me it retains the original format.

The exception that was raised (`Source format is multi-layer, but destination format is single-layer...`) is only raised when ImageProcessing gem detects that there are "<destination-path>-[0,1,2,...].<ext>" files created, which happens when you're converting from a multi-layer to a single-layer format (as the exception says). You can try running `pipeline.call(tempfile, allow_splitting: true)`, and you should see these kind of files being created on disk.

Note that the proper way to create a new Tempfile with an extension is by passing an array of basename and extension:

```rb
tempfile = Tempfile.new([File.basename(path), File.extname(path)])
```

**Comment by timcraft** [comment]
> The problem is not the Tempfile argument, but that the Tempfile you're created doesn't have an extension, and it's used as the destination path. I think that confused ImageMagick, maybe it doesn't know to which format you want to convert. I'm not able to reproduce that, however, for me it retains the original format.

ImageMagick seemed to be detecting the format ok without the extension, and I wasn't trying to convert formats. I am testing with imagemagick@6 though 🤷‍♂️

> Note that the proper way to create a new Tempfile with an extension is by passing an array of basename and extension:

Yep, either that or using `allow_splitting: true` option makes things work. Thanks!
