### ISSUE TITLE
Using Vips::Image Sources (Not Files) & Sharpen 

### ISSUE THREAD

**Issue by metaskills** [janko/image_processing#55]
I'm doing some work with Lambda to layer and compose images from S3. As such, I am avoiding reading & writing to files using `.source` with Vips::Images and `.call(save: false)` in my pipelines. I found a very strange behavior because of it. Essentially heavily pixelated layers, seen below.

| Layer | Final |
| --- | --- |
| ![bride-squad-layer](https://user-images.githubusercontent.com/2381/62777609-02f78e00-ba7c-11e9-932e-eb8a74d251a7.png) | ![bride-squad-final](https://user-images.githubusercontent.com/2381/62777622-0b4fc900-ba7c-11e9-96aa-9ab07cde5db9.png) |

If the layer file were saved to disk and read back in, it would be fine. The data is identical, however I did find that the format of the Vips::Image when run thru things like `resize_and_pad` and `resize_to_fill` end up having a format of `float` vs `uchar` when read back from disk. 

I was able to address this and get clean results by calling `.cast('uchar')` and the end of my pipelines. But, I did end up finding out that the source of the change from uchar to float came from the `ImageProcessing::Vips::Processor::SHARPEN_MASK` and auto sharpening #22 which BTW is a great feature! Below is an example of the layer image before and after sharpening within the `thumbnail` method. 

```
#<Image 900x825 uchar, 4 bands, srgb>
#<Image 900x825 float, 4 bands, srgb>
```

So, any advice on this? I like the sharpening feature. Rather than disabling it I'd like to maybe do a `ImageProcessing::Vips::Processor.const_set(:SHARPEN_MASK, ..)` or something with one that is the same but leaves my image as `uchar` or should I just tack on the `.cast('uchar')` as needed on the end of my pipelines?

Thanks in advance!

**Comment by janko** [comment]
It would be very useful if you could come up with a self-contained example that reproduces this issue, and shows a workaround. So, in this case the sharpening actually makes quality *worse*? The conversion from `uchar` to `float` happens *only* when using sharpening? Is this behaviour specific to PNGs?

How exactly is it related to using disk vs memory? I thought that image data dumped to and loaded from disk be exactly the same as data that was dumped to and loaded from memory.

A self-contained example that reproduces this issue would really help pinpoint whether the problem is in ImageProcessing or ruby-vips/libvips itself.

**Comment by metaskills** [comment]
> A self-contained example that reproduces this issue would really help pinpoint whether the problem is in ImageProcessing or ruby-vips/libvips itself.

Agreed, given these two files:

* design.png - https://user-images.githubusercontent.com/2381/62779808-30473a80-ba82-11e9-8657-26d2ae44ce72.png
* bg.png - https://user-images.githubusercontent.com/2381/62779747-1279d580-ba82-11e9-8199-c439cbd021be.png

The following code should duplicate the issue.

```ruby
design = ImageProcessing::Vips.source('./design.png').rotate(-12).resize_and_pad(145, 145).call(save: false)
final  = ImageProcessing::Vips.source('./bg.png').composite(design, mode: :over, gravity: 'north-west', offset: [219, 438]).call(save: false)
File.open('./final.png', 'wb') { |f| f.write(final.write_to_buffer('.png')) }
```

Things I have found change the behavior that led to me to believe the `ImageProcessing::Vips::Processor::SHARPEN_MASK` is the result. Both essentially re cast the Vips::Image to `uchar` format.

* If you save the `design` to disk and read it back in again using `Vips::Image.new_from_file`.
* If you add `.cast(:uchar)` to the end of the line where you set `design`.

**Comment by jcupitt** [comment]
Hi, I think it might be here:

https://github.com/janko/image_processing/blob/master/lib/image_processing/vips.rb#L143

`conv()` defaults to float precision. You have to select the fast int path if you you are using an int convolution mask (as you are). I would try:

```
image = image.conv(sharpen, precision: :int) if sharpen
```

Bonus: this should give a speed-up, since int convolutions will use SIMD.

**Comment by metaskills** [comment]
Thanks a ton! @janko would you like me to make a pull request with that change?

**Comment by janko** [comment]
Nice find @jcupitt! @metaskills yes, feel free to make a PR 👍
