### ISSUE TITLE
VIPS: strip does not work with libvips 8.9.0

### ISSUE THREAD

**Issue by renchap** [janko/image_processing#64]
Using `saver(strip: true)` no longer works due to a change in libvips 8.9.0:
```
pipeline = ImageProcessing::Vips.source(file).saver(quality: 90, interlace: true, strip: true)
versions[:s1200] = pipeline.resize_to_limit!(1200, 1200)
versions[:h600] = pipeline.resize_to_limit!(nil, 600)
versions[:h300] = pipeline.resize_to_limit!(nil, 300)
```

results in
```
VIPS-WARNING **: 16:58:48.677: can't remove metadata "orientation" on shared image
VIPS-WARNING **: 16:58:48.677: can't remove metadata "exif-ifd0-Orientation" on shared image
```

The change is caused by the breaking change mentioned in the 8.9.0 blog post: https://libvips.github.io/libvips/2019/12/11/What's-new-in-8.9.html

**Comment by janko** [comment]
Thanks for the report. Would you mind creating a minimal self-contained script that reproduces the problem? I'm not getting any errors/warnings when I attempt the same (I'm on macOS Catalina):

```rb
require "image_processing/vips"

Vips.version_string # => "8.9.0-Mon Jan  6 14:10:21 UTC 2020"

vips = ImageProcessing::Vips
  .source("test/fixtures/portrait.jpg")
  .saver(quality: 90, interlace: true, strip: true)

vips.resize_to_limit!(100, 100)
vips.resize_to_limit!(200, 200)
vips.resize_to_limit!(300, 300)
```

ImageProcessing doesn't reuse image objects by default, so I'm not sure where the exception is coming from, or what should be course of action.

**Comment by ledermann** [comment]
I got similar errors since Homebrew updated to vips `8.9.0-Mon Jan  6 14:10:21 UTC 2020` (on my macOS Catalina machine). Beside the warnings, auto rotation does not work at all from within a Rails application (which uses ActiveStorage and :vips as variant processor)

@janko: Your code snippet works fine here, but after changing the source file to "test/fixtures/rotated.jpg", I get the same warnings @renchap reported above:

```
VIPS-WARNING **: 07:03:41.451: can't remove metadata "orientation" on shared image
VIPS-WARNING **: 07:03:41.451: can't remove metadata "exif-ifd0-Orientation" on shared image
```

Tested with:

* image_processing 1.10.2
* ruby-vips 2.0.17
* ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]

**Comment by janko** [comment]
Thanks for the details, I was able to reproduce now too 👍 

It seems the warning is coming from the `vips_thumbnail()` function. With `ruby-vips` directly we can reproduce it with the following script:

```rb
require "vips"

image = Vips::Image.new_from_file("test/fixtures/rotated.jpg")
image.thumbnail_image(300)
```
```
VIPS-WARNING **: 08:41:46.750: can't remove metadata "orientation" on shared image
VIPS-WARNING **: 08:41:46.750: can't remove metadata "exif-ifd0-Orientation" on shared image
```

I tried adding `image = image.copy` before thumbnailing (as suggested by the release notes), but the warning is still there. This leads me to believe this is a bug inside `vips_thumbnail()` itself, as I would expect libvips to internally create a copy of the image if it needs to edit any metadata (in this case orientation).

If I disable libvips cache, the warning goes away:

```rb
require "vips"

Vips.vips_cache_set_max 0 # disable libvips cache

image = Vips::Image.new_from_file("test/fixtures/rotated.jpg")
image.thumbnail_image(300) # no warning
```

If I disable autorotation, the warning goes away:

```rb
require "vips"

image = Vips::Image.new_from_file("test/fixtures/rotated.jpg")
image.thumbnail_image(300, no_rotate: true) # no warning
```

Seeing https://github.com/libvips/libvips/issues/1515 suggests this is likely a bug in libvips 8.9.0.

**Comment by ledermann** [comment]
Thanks for investigation, @janko! 

Because disabling libvips caching didn't fix auto-rotating in my Rails app, I reverted my libvips installation back to 8.8.4_1 using this Homebrew commands:

```bash
brew uninstall vips
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/d5f2601ac0ce342b96063576b7c27455688ed9d8/Formula/vips.rb
```

Now waiting for a fixed release of libvips.

**Comment by janko** [comment]
I tried running the ImageProcessing test suite on libvips 8.9.0, and to my surprise all tests are passing. They are not printing any warnings either because I've set `ENV["VIPS_WARNINGS"] = "0"`.

I ran the following script which tests different auto-rotation mechanisms to see which one actually works:

```rb
require "vips"
require "tempfile"

source = "test/fixtures/rotated.jpg"

images = {
  default:                 Vips::Image.new_from_file(source),
  autorot:                 Vips::Image.new_from_file(source).autorot,
  autorotate:              Vips::Image.new_from_file(source, autorotate: true),
  thumbnail_image:         Vips::Image.new_from_file(source).thumbnail_image(600),
  thumbnail:               Vips::Image.thumbnail(source, 600),
  autorot_thumbnail_image: Vips::Image.new_from_file(source).autorot.thumbnail_image(600),
}

results = images.transform_values do |image|
  result = Tempfile.new %w[result .jpg]
  image.write_to_file(result.path)
  result
end

html = ""

results.each do |name, result|
  html << %(<div><p>#{name}</p><img src="file://#{result.path}" /></div>)
end

File.write("page.html", html)

gets
```

I chose to show images on an HTML page because browsers ignore orientation metadata and just show the image as is, which tells me whether the image has been successfully auto-rotated. The results I got are almost the same on 8.9.0 and 8.8.4:

| operation | libvips 8.8.4 | libvips 8.9.0 | success |
| :-------- | :---------- | :--------- | :-------- |
| `default` | rotated | rotated | ✅ |
| `autorot` | upright | upright | ✅ |
| `autorotate` | upright | upright | ✅ |
| `thumbnail_image` | upright | upright | ✅ |
| `thumbnail` | upright | upright | ✅ |
| **`autorot_thumbnail_image`** | **upright** | **rotated** | ❌  |

The latter is the scenario ImageProcessing hits when both resizing and loader options are specified (this is not @renchap's case). In this case, the resize-on-load execution branch is skipped (which would only call `Vips::Image.thumbnail` and would work), and instead both `vips_autorot()` and `vips_thumbnail_image()` are called, which seem to cancel each other out on libvips 8.9.0.

The image is should be correctly auto-rotated on 8.9.0 if one disables auto-rotation for the `vips_thumbnail()` operation:

```rb
ImageProcessing::Vips
  # ...
  .resize_to_limit(400, 400, no_rotate: true)
  # ...
```

or skips the `vips_autorot()` operation:

```rb
ImageProcessing::Vips
  # ...
  .loader(autorot: false)
  # ...
```

I will file a bug on the libvips repo and see if this might have been an unintended bug. Otherwise we'll have to find a fix. The problem is that `ImageProcessing::Vips::Processor.load_image` doesn't know whether the resize operation will be called (thus apply auto-rotation), neither does `ImageProcessing::Vips::Processor#thumbnail` know whether auto-rotation has been applied during loading (maybe the user had disabled it, relying on thumbnail auto-rotation).

**Comment by janko** [comment]
After discussing this with John in https://github.com/libvips/libvips/issues/1523, I decided to just disable auto-rotation when calling `Vips::Image.thumbnail_image`, so that the only auto-rotation performed is `Image#autorot` .

That behaviour makes sense to me in general, and is consistent with ImageMagick, where the thumbnail operation doesn't auto-rotate. I'll add some tests and try to release a new patch version.

**Comment by ledermann** [comment]
Great work, creating thumbnails with auto-rotation now works fine with both vips 8.8.4 and 8.9.0.
